# Generated by Django 4.0.2 on 2022-07-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ciry',
            new_name='city',
        ),
    ]
