# Generated by Django 4.0.2 on 2022-06-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
