# Generated by Django 4.0.2 on 2022-04-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_join',
            new_name='date_joined',
        ),
    ]
