# Generated by Django 4.0.6 on 2022-09-01 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='super_likes',
            field=models.ManyToManyField(blank=True, related_name='super_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
