# Generated by Django 4.0.6 on 2022-09-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_post_super_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='super_likes',
            new_name='slikes',
        ),
    ]
