# Generated by Django 4.0.6 on 2022-09-04 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_rename_super_likes_post_slikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='slikes',
            field=models.ManyToManyField(blank=True, related_name='comment_slikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slikes',
            field=models.ManyToManyField(blank=True, related_name='slikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
