# Generated by Django 4.0.2 on 2022-05-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
