from django.shortcuts import render
from school.models import Student
from datetime import date, time

# Create your views here.

def home(request):
    # student_data = Student.objects.all()
    # student_data = Student.objects.filter(name__exact='Hemi')
    # student_data = Student.objects.filter(name__iexact='hemi')
    # student_data = Student.objects.filter(name__iexact='hemi')
    # student_data = Student.objects.filter(name__contains='H')
    # student_data = Student.objects.filter(name__icontains='h')
    # student_data = Student.objects.filter(id__in = [1, 5, 7])
    # student_data = Student.objects.filter(marks__gt = 60)
    # student_data = Student.objects.filter(marks__gte = 60)
    # student_data = Student.objects.filter(marks__lt = 75)
    # student_data = Student.objects.filter(marks__lte = 75)
    # student_data = Student.objects.filter(name__startswith='S')
    # student_data = Student.objects.filter(name__istartswith='a')
    # student_data = Student.objects.filter(name__endswith='A')
    # student_data = Student.objects.filter(name__iendswith='a')
    # student_data = Student.objects.filter(passdate__range=('2017-01-01', '2022-01-01'))
    # student_data = Student.objects.filter(admdatetime__date=date(2017,6,15))
    # student_data = Student.objects.filter(admdatetime__date__gt=date(2017,6,15))
    # student_data = Student.objects.filter(passdate__year=2017)
    # student_data = Student.objects.filter(passdate__year__gt=2017)
    # student_data = Student.objects.filter(passdate__year__gte=2017)
    # student_data = Student.objects.filter(passdate__month=5)
    # student_data = Student.objects.filter(passdate__month__gt=5)
    # student_data = Student.objects.filter(passdate__month__gte=5)
    # student_data = Student.objects.filter(passdate__day=15)
    # student_data = Student.objects.filter(passdate__day__gt=15)
    # student_data = Student.objects.filter(passdate__day__gte=15)
    # student_data = Student.objects.filter(passdate__week=23)
    # student_data = Student.objects.filter(passdate__week__gt=23)
    # student_data = Student.objects.filter(passdate__week_day=5)
    # student_data = Student.objects.filter(passdate__week_day__gt=5)
    # student_data = Student.objects.filter(passdate__week_day__gte=5)
    # student_data = Student.objects.filter(passdate__quarter=3)
    # student_data = Student.objects.filter(passdate__quarter__gt=2)
    # student_data = Student.objects.filter(passdate__quarter__gte=2)
    # student_data = Student.objects.filter(admdatetime__time=time(10))
    # student_data = Student.objects.filter(admdatetime__time__gt=time(10,00))
    # student_data = Student.objects.filter(admdatetime__time__gte=time(10,00))
    # student_data = Student.objects.filter(admdatetime__hour=5)
    # student_data = Student.objects.filter(admdatetime__hour__gt=5)
    # student_data = Student.objects.filter(admdatetime__hour__gte=5)
    # student_data = Student.objects.filter(admdatetime__minute=5)
    # student_data = Student.objects.filter(admdatetime__minute__gt=5)
    # student_data = Student.objects.filter(admdatetime__minute__gte=45)
    # student_data = Student.objects.filter(admdatetime__second=45)
    # student_data = Student.objects.filter(admdatetime__second__gt=45)
    # student_data = Student.objects.filter(admdatetime__second__gte=45)
    # student_data = Student.objects.filter(roll__isnull=True)
    student_data = Student.objects.filter(roll__isnull=False)

    print('Return', student_data)
    print()
    print('SQL Query', student_data.query)
    return render(request, 'school/home.html', {'students': student_data})